name = "project-inventory"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages 构建输出目录
pages_build_output_dir = ".open-next/worker"

# D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "project-inventory"
database_id = "46c27205-1e03-44b4-bd40-2ea64bd769e3"

[vars]
NEXT_PUBLIC_APP_URL = "https://project-inventory.pages.dev"
